extends Node2D

var nombres_f = ["Abril", "Aitana", "Alba", "Alicia", "Alma", "Amalia", "Ana", "Andrea", "Ángela", "Ariadna", "Aurora", "Bárbara", "Beatriz", "Belén", "Berta", "Blanca", "Bruna", "Camila", "Candela", "Carla", "Carlota", "Carmen", "Carolina", "Catalina", "Celia", "Clara", "Claudia", "Cristina", "Daniela", "Diana", "Dolores", "Elena", "Elisa", "Elsa", "Emma", "Esther", "Eva", "Fabiola", "Fátima", "Fernanda", "Gabriela", "Gema", "Gloria", "Guadalupe", "Inés", "Irene", "Iris", "Isabel", "Jana", "Jimena", "Julia", "Lara", "Laura", "Leire", "Leonor", "Leticia", "Lidia", "Lola", "Lorena", "Lucía", "Luna", "Macarena", "Manuela", "Mar", "María", "Marina", "Marta", "Martina", "Mía", "Miriam", "Mónica", "Nadia", "Natalia", "Nerea", "Noelia", "Nuria", "Olivia", "Olga", "Paola", "Patricia", "Paula", "Pilar", "Raquel", "Rebecca", "Rocío", "Rosa", "Ruth", "Sabina", "Sara", "Sofía", "Sonia", "Tania", "Teresa", "Valentina", "Valeria", "Vanesa", "Verónica", "Victoria", "Yolanda", "Zoe"]
var nombres_m = ["Aarón", "Abel", "Adrián", "Agustín", "Alejandro", "Andrés", "Antonio", "Arturo", "Baltasar", "Benjamín", "Bernardo", "Borja", "Bruno", "Camilo", "Carlos", "César", "Claudio", "Cristian", "Damián", "Daniel", "Darío", "David", "Diego", "Edgar", "Eduardo", "Elías", "Emilio", "Enrique", "Esteban", "Fabián", "Federico", "Felipe", "Fernando", "Francisco", "Gabriel", "Gael", "Gerardo", "Gonzalo", "Guillermo", "Héctor", "Hernán", "Hugo", "Ian", "Iker", "Isaac", "Ismael", "Iván", "Jaime", "Javier", "Jesús", "Joaquín", "Jorge", "José", "Juan", "Kevin", "Kilian", "Leandro", "Leo", "Leonardo", "Lorenzo", "Lucas", "Luis", "Manuel", "Marcos", "Mario", "Martín", "Mateo", "Matías", "Miguel", "Nicolás", "Noé", "Oliver", "Omar", "Óscar", "Pablo", "Patricio", "Pedro", "Rafael", "Ramiro", "Ramón", "Raúl", "Ricardo", "Roberto", "Rodrigo", "Rubén", "Salvador", "Samuel", "Santiago", "Sebastián", "Sergio", "Tadeo", "Tomás", "Ulises", "Uriel", "Vicente", "Víctor", "Walter", "Xavier", "Yago", "Zacarías"]
var apellidos = ["Abad", "Aguilar", "Alonso", "Álvarez", "Arias", "Barrios", "Beltrán", "Benítez", "Blanco", "Bravo", "Burgos", "Cabrera", "Calvo", "Campos", "Cano", "Carrasco", "Castillo", "Castro", "Cortés", "Cruz", "Delgado", "Díaz", "Domínguez", "Espinosa", "Estévez", "Fernández", "Ferrer", "Flores", "Fuentes", "Gallardo", "Gallego", "García", "Giménez", "Gómez", "González", "Guerrero", "Gutiérrez", "Hernández", "Herrera", "Hidalgo", "Ibáñez", "Iglesias", "Jiménez", "Juárez", "Lara", "León", "López", "Lozano", "Luna", "Marín", "Márquez", "Martín", "Martínez", "Medina", "Méndez", "Mendoza", "Miranda", "Molina", "Montero", "Morales", "Moreno", "Muñoz", "Navarro", "Nieto", "Núñez", "Ortega", "Ortiz", "Pacheco", "Padilla", "Palacios", "Pardo", "Parra", "Pascual", "Pastor", "Pérez", "Prieto", "Quintana", "Quiroga", "Ramírez", "Ramos", "Rivera", "Robles", "Rodríguez", "Rojas", "Romero", "Rubio", "Ruiz", "Saavedra", "Sáez", "Salazar", "Sanz", "Serrano", "Silva", "Soto", "Suárez", "Torres", "Vargas", "Vázquez", "Vega", "Zúñiga"]
#nombres y apellidos disponibles para los personajes


var nombre = nombres_f.pick_random() + " " + apellidos.pick_random() + " " + apellidos.pick_random()
func _ready() -> void:
	print(nombre)
